theme = "hugo-theme-relearn-main"

[params]
linkTitle = 'Java & Container'
author.name = 'maeddes'
themeVariant = [
	{ identifier = 'relearn-dark'   },
	{ identifier = 'zen-auto',      name = 'Zen Light/Dark', auto = [ 'zen-light', 'zen-dark' ] },
	{ identifier = 'zen-dark'       },
	{ identifier = 'retro-auto',    name = 'Retro Learn/Neon', auto = [ 'learn', 'neon' ] },
	{ identifier = 'red'            }
]


# For search functionality
[outputs]
home = ["HTML", "RSS", "SEARCH", "SEARCHPAGE"]
