FROM eclipse-temurin:21-jre AS builder
WORKDIR /application
COPY target/simplecode-0.0.1-SNAPSHOT.jar application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM eclipse-temurin:21-jre
WORKDIR /application
COPY --from=builder /application/dependencies/ ./
COPY --from=builder /application/spring-boot-loader/ ./
COPY --from=builder /application/snapshot-dependencies/ ./
COPY --from=builder /application/application/ ./
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar ./
ENTRYPOINT ["java","-javaagent:/application/opentelemetry-javaagent.jar","org.springframework.boot.loader.launch.JarLauncher"]


